name: Package Audit

on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 1 * *" # every month

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - run: npm audit --omit dev
